safe:        true
markdown: kramdown
exclude: [node_modules, bower_components, vendor]
url: https://jhipster.ddocs.cn
github_repository_url: https://github.com/jhipster/jhipster.github.io
kramdown:
  input: GFM
https://jhipster.ddocs.cn/:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
defaults:
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
